/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ftgCrossChainTravelVaultSol from "./FTG_CrossChainTravelVault.sol";
export type { ftgCrossChainTravelVaultSol };
export type { XRPToFlareConverter } from "./XRPToFlareConverter";
