/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFdcVerification,
  IFdcVerificationInterface,
} from "../../../contracts/FTG_CrossChainTravelVault.sol/IFdcVerification";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFdcVerification__factory {
  static readonly abi = _abi;
  static createInterface(): IFdcVerificationInterface {
    return new Interface(_abi) as IFdcVerificationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFdcVerification {
    return new Contract(address, _abi, runner) as unknown as IFdcVerification;
  }
}
