/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFtsoV2FeedConsumer,
  IFtsoV2FeedConsumerInterface,
} from "../../../contracts/FTG_CrossChainTravelVault.sol/IFtsoV2FeedConsumer";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes21",
        name: "feedId",
        type: "bytes21",
      },
    ],
    name: "getFeedById",
    outputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "uint64",
        name: "timestamp",
        type: "uint64",
      },
      {
        internalType: "uint8",
        name: "decimals",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFtsoV2FeedConsumer__factory {
  static readonly abi = _abi;
  static createInterface(): IFtsoV2FeedConsumerInterface {
    return new Interface(_abi) as IFtsoV2FeedConsumerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFtsoV2FeedConsumer {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IFtsoV2FeedConsumer;
  }
}
