/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IXRPLPaymentVerification,
  IXRPLPaymentVerificationInterface,
} from "../../../contracts/FTG_CrossChainTravelVault.sol/IXRPLPaymentVerification";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "transactionId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "sourceAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "destinationAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "paymentReference",
        type: "bytes32",
      },
    ],
    name: "verifyPayment",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IXRPLPaymentVerification__factory {
  static readonly abi = _abi;
  static createInterface(): IXRPLPaymentVerificationInterface {
    return new Interface(_abi) as IXRPLPaymentVerificationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IXRPLPaymentVerification {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IXRPLPaymentVerification;
  }
}
